### ISSUE TITLE
Tareas

### ISSUE THREAD

**Issue by Juan-Cruz-Rey** [JuanCruzMonteros/Grupo_601#2]
# To-do list
## Pantallas
- [x] Crear pantalla de Login.
- [x] Crear pantalla de Registrar.
- [x] Crear pantalla de Eventos capturados (tabla).(Faltaria cargarlos en la tabla)
    - [x] Evento - Hora - Sensor utilizado - Estado sensor.
- [x] Crear pantalla ataque en curso.
    - [x] Boton de "Evento terminado".
    - [x] Tiempo sucedido (timer) desde que arranco el ataque.

## Eventos
- [x] Validar conexión a internet
- [x] Logear evento de conexión a internet (Cuando se pierde que logee en el servidor).)
    (Esto al medio dia lo hacemos en background en dos minutos, falta solo agregarlo)
- [x] Logear evento de GPS.
- [x] Logear evento de Shake.
- [x] Guardar eventos en SharedPreferences.

## Performance
- [x] Pruebas de respuesta fluida.
- [x] Liberación de recursos.
- [x] Cambios de estado.
- [x] Errores de conexión

## Otros
- [x] Implementar ejecución en background.
